# Generated by Django 3.0 on 2020-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/'),
        ),
    ]
