# Generated by Django 3.0.2 on 2020-01-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200131_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel'),
        ),
    ]
