# Generated by Django 3.0.2 on 2020-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_auto_20200131_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.FileField(default='https://drive.google.com/open?id=16ZU24pGnhv3UUrdbb6vQSagFGiKHLMWX', upload_to=''),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
