# Generated by Django 3.0 on 2020-02-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200201_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.FileField(upload_to='profile_pic'),
        ),
    ]
