# Generated by Django 3.0 on 2020-02-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200201_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='profile_pic',
        ),
    ]
