# Generated by Django 3.0 on 2020-02-01 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_remove_personalinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.ImageField(default='/media/profile_pic/user_default.png', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
