# Generated by Django 3.0.2 on 2020-01-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.FileField(default='https://drive.google.com/open?id=16ZU24pGnhv3UUrdbb6vQSagFGiKHLMWX', upload_to='static', verbose_name='Hello'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='roll_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
