# Generated by Django 3.0 on 2020-01-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200131_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='mobile_number',
        ),
    ]
