# Generated by Django 3.0 on 2020-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200201_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/user_default.png', upload_to='profile_pic/'),
        ),
    ]
